version: '3.7'
services:
  php:
    container_name: php
    build: ./php-fpm
    ports:
    - "9000:9001"
    volumes:
    - ./app:/var/www/app
    - ./logs/app:/var/www/app/var/log
    extra_hosts:
    - "docker-host.localhost:127.0.0.1"
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
    - "80:80"
    volumes:
    - ./logs/nginx:/var/log/nginx
networks:
  default:
    driver: bridge